name: Sync Github Repos To Myliving
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Github Repos To Myliving  # 名字随便起
      uses: Yikun/hub-mirror-action@master  # 使用Yikun/hub-mirror-action
      with:
        src: github/lzpeng723  # 源端账户名(github)
        dst: myliving.top:58022/lzpeng723  # 目的端账户名(myliving.top)
        dst_key: ${{ secrets.KD_MYLIVING_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.KD_MYLIVING_TOKEN }}  # Myliving账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "https"  # 使用http方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "servicetools"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作
